# Generated by Django 4.1 on 2022-08-20 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mng_app', '0004_employee_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='sno',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
