# Generated by Django 4.1 on 2022-08-20 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mng_app', '0006_remove_department_id_alter_department_sno'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='sno',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
